export const welcomeMessages = [
  'Every word you learn is a step closer to fluency. Keep pushing forward with confidence!',
  'Great progress so far! Let’s aim for another lesson today and grow your skills even more.',
  'You’re building strong language habits. Stay focused and the results will follow soon!',
  'Remember: Small daily efforts lead to big changes. You’re doing really well!',
  'Your English is improving every day. Let’s keep up the momentum together!',
  'Stay curious and keep practicing — progress comes with every new word you learn.',
  'You’ve shown great dedication this week. Just a little more, and you’ll hit your goals!',
  'Keep your eyes on the goal. You’re closer than you think — just one step at a time!',
  "Learning takes time and patience. Keep going, you're doing a fantastic job!",
  'Each lesson you complete is a victory. Celebrate your progress and keep it going!',
  'Consistency is key. Keep showing up and you’ll be amazed at what you achieve.',
  'Your effort today will pay off tomorrow. Stay motivated and keep moving forward!',
  'Mistakes are part of learning. Embrace them and grow stronger every day.',
  'You’re on an exciting journey. Keep exploring new words and expressions!',
  'Celebrate every small success — they add up to big achievements over time.',
  'Your passion for learning is inspiring. Keep that fire burning bright!',
  'Focus on progress, not perfection. You’re improving with every step you take.',
  'Never underestimate the power of practice. Your dedication is paying off!',
  'Believe in yourself and your ability to master new skills. You’ve got this!',
];
